### PR TITLE
Add tutorials on how to create a Sourcegraph account and how to insta…

### PR DESCRIPTION
**Pull request by Princesso**
Sourcegraph with Docker Compose
How to create an account with Sourcegraph

## Type of change

Tutorial

### What should this PR do?

[How to install Sourcegraph with Docker Compose](https://sourcegraph.atlassian.net/browse/DEVED-101?atlOrigin=eyJpIjoiZGY5YzRiMTNkNGEyNGE4N2JiMDk4N2M5YjZlZDc3MTQiLCJwIjoiaiJ9)

[How to create an account on Sourcegraph Cloud](https://sourcegraph.atlassian.net/browse/DEVED-97?atlOrigin=eyJpIjoiZmIxMGZmOWRkNjhhNGVhYWEwNGY1YzcyNTc0NzBmZjEiLCJwIjoiaiJ9)
[How to create an account on self hosted Sourcegraph](https://sourcegraph.atlassian.net/browse/DEVED-97?atlOrigin=eyJpIjoiZmIxMGZmOWRkNjhhNGVhYWEwNGY1YzcyNTc0NzBmZjEiLCJwIjoiaiJ9)

## Pull request process

**Reviewers**:

1. Test functionality using the criteria above.
2. Offer tips for efficiency, feedback on best practices, and possible alternative approaches and things that may not have been considered.
3. For shorter, "quick" PRs, use your best judgement on #​2.
4. Use a collaborative approach and provide resources and/or context where appropriate.
5. Provide screenshots/grabs where appropriate to show findings during review.

**Reviewees**:

1. Prefer incremental and appropriately-scoped changes.
2. Leave a comment on things you want explicit feedback on.
3. Respond clearly to comments and questions.

### CODE REVIEW

**Comment by ltagliaferri** [comment]
Hi Princess, what does the "self review" tag mean?

**Comment by Princesso** [comment]
> Hi Princess, what does the "self review" tag mean?

@ltagliaferri , it means that I am giving it a look before moving it for team review. Sometimes, I might need to check out what the preview looks like to catch anything that was missed before sending it for team reviews.

Does this provide enough context?

**Comment by ltagliaferri** [comment]
> > Hi Princess, what does the "self review" tag mean?
> 
> @ltagliaferri , it means that I am giving it a look before moving it for team review. Sometimes, I might need to check out what the preview looks like to catch anything that was missed before sending it for team reviews.
> 
> Does this provide enough context?

I think keeping the PR as a draft with the `WIP` label is sufficient for this use case

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
I'll give feedback on Google docs, though the two account creation tutorials are currently in one doc and should be separated. Can you also remove the images from this pull request as you have uploaded them to GCP? Thank you

**Pull request closed without merging**
