### PR TITLE
Add flag to show or hide table of contents

### PR DESCRIPTION
**Pull request by Princesso**
## Type of change

Feature

### What should this PR do?

Adds a flag to display or hide table of content
[DEVED-3](https://sourcegraph.atlassian.net/browse/DEVED-3?atlOrigin=eyJpIjoiMDk4NDFkMWU5MjA3NDQ5YjhlZmIzZjU1MDRjOGJhOGIiLCJwIjoiaiJ9)

### Why are we making this change?

We want to be able to hide or show table of content at will

### What are the acceptance criteria? 

When a user sets the showToc flag on a resource, the Table of content should be shown or hidden, depending on the boolean value of the flag

### How should this PR be tested?

- Pull and checkout to this branch
- Set the `showToc` flag on any resource
- Open the resource on the browser and see table of content hidden or show, depending on the value you set

## Screenshots
Screenshot 2021-07-30 at 19 07 31

## Pull request process

**Reviewers**:

1. Test functionality using the criteria above.
2. Offer tips for efficiency, feedback on best practices, and possible alternative approaches and things that may not have been considered.
3. For shorter, "quick" PRs, use your best judgement on #​2.
4. Use a collaborative approach and provide resources and/or context where appropriate.
5. Provide screenshots/grabs where appropriate to show findings during review.

**Reviewees**:

1. Prefer incremental and appropriately-scoped changes.
2. Leave a comment on things you want explicit feedback on.
3. Respond clearly to comments and questions.

### CODE REVIEW

**Comment by katjuell** [comment]
Before I review this, can I just get some clarity on why we are adding this? What is the use case or necessity? I see some discussion in the ticket, but I'm still not clear on it. cc @ltagliaferri @marekweb

**Comment by ltagliaferri** [comment]
> Before I review this, can I just get some clarity on why we are adding this? What is the use case or necessity? I see some discussion in the ticket, but I'm still not clear on it. cc @ltagliaferri @marekweb

@marekweb I'm not sure if I know the original thinking behind this and if that thinking is still the same at this point in time. Can you add some context here? Thanks!

**Comment by marekweb** [comment]
The original thinking is to allow for content that doesn't translate into a table-of-contents structure in a useful way.

We don't currently have any piece of content that requires this, so it's a forward-looking feature, and a nice-to-have.

The content that comes closest to being a use case is the [search video](https://learn.sourcegraph.com/three-ways-to-search-video) because it only shows "Contents: Transcript" which is not particularly helpful because there's only one item.

This feature would become more useful in the future if the field can specify what alternative content to display in the column instead of the TOC. Then it would be part of a set of hypothetical features that give the content author some control and customization of the layout of the page.

**Comment by katjuell** [comment]
My vote would be to wait on this feature until we are at the point of needing it, though I can see the utility for the video `post`. However, I'm imagining that down the road, `video` (with transcript) could be its own content type, with its own `template`, which we could customize to return only what we need etc.

Happy to defer to whatever you think is best @ltagliaferri @marekweb since I realize I'm coming to this conversation later than you were originally having it. If you'd like to keep the feature, then I can hop on a review.

**Comment by ltagliaferri** [comment]
I think the videos could benefit from more organizational intervention in any case to make them easier for readers to digest, I would advocate for headings in transcripts and a heading for the video to make it more digestible and also clear from an accessibility standpoint, which would translate to a table of contents.

**Pull request closed without merging**
