### PR TITLE
Add alt for header images on post index and post pages

### PR DESCRIPTION
**Pull request by katjuell**
Resolves this [Asana ticket](https://app.asana.com/0/1200612380814575/1200512359516128/f) to add `alt` text to header images by ensuring the `alt` text is available on the existing records themselves and passed appropriately to the relevant components.

NB: The `alt` text is not a dependency here, so if it is not supplied, it will be set to be empty.

### To Test
- Check out branch and ensure that `alt` text is present on header images on both the list items at `/` and individual `/record-slug`s.
- Remove the `imageAlt` text from a record of your choice, and check that everything still renders correctly, and `alt` text is not present.

### CODE REVIEW

**Comment by marekweb** [comment]
Great! I like your idea of creating a new markdown field for this, that makes sense.

For our header illustration images (the abstract geometric ones) they could be considered [decorative images](https://www.w3.org/WAI/tutorials/images/informative/) that aren't part of the content. In that case, the recommendation seems to be to use an empty string alt value, `alt=""`. Does thjis guidelines apply here?

**Comment by ltagliaferri** [comment]
I agree that the current banners are decorative images but the future plan is for us to get more dynamic ones (with titles or illustrations related to the content?). I am ok with following the w3 / [a11y](https://www.a11yproject.com/checklist/) guidelines and leave these empty if everyone agrees they are decorative images, or else we can write "Sourcegraph Learn" in the alt text since that is what it says on the banner and it doesn't say it anywhere else on the site. Thoughts?

**Comment by katjuell** [comment]
Ohhh cool — yeah, I would be down for "Sourcegraph Learn" if other folks are. I guess if we consider that they are branding for the Learn web property, maybe that would be a case for them not being *purely* decorative?

**Review by marekweb — APPROVED** [review]

**Review by ltagliaferri — APPROVED** [review]
I updated this with the "Sourcegraph Learn" tags in the banners since the images have this text in them, while not noting the abstract/decorative nature of the images. As we have new / more dynamic banners our approach to this will likely evolve going forward. We may also seek out a consult with accessibility subject matter experts

**Pull request merged**
