### PR TITLE
Update node version to 16.5

### PR DESCRIPTION
**Pull request by marekweb**
Update the node version in `.nvmrc` from 16.1 to 16.5.

This affects the node version that will be used when running the `nvm install`  command.

When deploying to Netlify, this is the version of node that is used in the build process.

### CODE REVIEW

**Comment by ltagliaferri** [comment]
Any concerns about this, @katjuell ?

**Comment by katjuell** [comment]
I think we will need an updated `package-lock.json`, no?

**Comment by katjuell** [comment]
@marekweb @ltagliaferri looks okay to me with new dependencies. `npm ci` on the branch with correct version of Node to confirm?

**Comment by katjuell** [comment]
Also, I am not getting mention notifications to my email on PRs, which is weird. If y'all have thoughts, please lmk! Like, I got a notification when you merged `main` Lisa, but not when you mentioned me.

**Comment by ltagliaferri** [comment]
Thanks, @katjuell, maybe check your subscription settings / defaults re: notifications?

**Comment by katjuell** [comment]
i've been looking, but as far as I can see I am subscribed to all mentions? I haven't run into this before, will keep digging.

**Pull request merged**
