### PR TITLE
Series dropdown menu

### PR DESCRIPTION
**Pull request by katjuell**
### What should this PR do?
Resolves [DEVED-265](https://sourcegraph.atlassian.net/browse/DEVED-265) by updating our collection list to be a dropdown menu with toggle.

### Why are we making this change?
We want to improve navigation within the site and on all pages.

### What are the acceptance criteria? 
- Series list should display in a full-width column above tutorials and ToC.
- Series list should include series name and the title of the first tutorial in the series in the header.
- Series header should include an icon toggle that, when clicked, reveals a modal with the other tutorial titles in the series.
- Toggle should open and close the modal.
- The current tutorial in the series should be highlighted.
- Mobile styles should look normal.

## Pull request process

**Reviewers**:

1. Test functionality using the criteria above.
2. Offer tips for efficiency, feedback on best practices, and possible alternative approaches and things that may not have been considered.
3. For shorter, "quick" PRs, use your best judgement on #​2.
4. Use a collaborative approach and provide resources and/or context where appropriate.
5. Provide screenshots/grabs where appropriate to show findings during review.

**Reviewees**:

1. Prefer incremental and appropriately-scoped changes.
2. Leave a comment on things you want explicit feedback on.
3. Respond clearly to comments and questions.

### CODE REVIEW

**Comment by katjuell** [comment]
Screen Shot 2021-11-29 at 1 27 07 PM
Screen Shot 2021-11-29 at 1 27 14 PM
Screen Shot 2021-11-29 at 1 27 25 PM
Screen Shot 2021-11-29 at 1 27 33 PM
Screen Shot 2021-11-29 at 1 27 50 PM

**Comment by katjuell** [comment]
Some questions I have for you @ltagliaferri:
- How do you feel about the toggle icon?
- ^^ border on the header?
- ^^ border on the dropdown modal? Should that be lighter?

**Comment by ltagliaferri** [comment]
Feel good about the toggle icon, I think the border on the dropdown modal can be lighter.

**Comment by katjuell** [comment]
Sweet — thanks!

**Review by ltagliaferri — APPROVED** [review]
This looks good, I think the lighter border is better than the darker one 🚀

**Pull request merged**
